### ISSUE TITLE
请问tensorflow1.12可以不，我的安装deepctr失败

### ISSUE THREAD

**Issue by sportzhang** [shenweichen/Bytedance_ICME2019_challenge_baseline#5]

**Comment by shenweichen** [comment]
@KAIKAIZHANG tensorflow1.12是可以的 请具体贴一下报错的信息~

**Comment by sportzhang** [comment]
![image](https://user-images.githubusercontent.com/16151674/53167986-7fa0c800-3614-11e9-8380-05ab60338812.png)
我是在linux系统的python虚拟环境下安装的！linux版本为Ubuntu16.04

**Comment by shenweichen** [comment]
@KAIKAIZHANG 这个问题是由于你的linux系统没有网络连接导致的哈~ 建议自己单独装一下`tensorflow`或者`tensorflow-gpu` 然后使用命令`pip install xxx.whl --no-deps`安装
